### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tharatau**

### CODE REVIEW

**Review by zkrige — APPROVED** [review]

**Comment by zkrige** [comment]
@tharatau it looks like the path for the release files has changed

 instead of `release/mac/*.zip` it looks like it should be `mac/*.zip` - the same for linux and windows. 

Will you modify this in your workflow file and amend the PR?

**Comment by zkrige** [comment]
@tharatau hmm actually im not sure

the previous release that DID work properly looked similar. Do you think perhaps its an issue with the tags/refs?

image

**Comment by tharatau** [comment]
Just set write permissions - could you retry the failed job?

**Comment by zkrige** [comment]
it failed again but it looks like it might be failing on refs

image

can you comment the refs part out of your workflow and see if it works then?

**Comment by tharatau** [comment]
I'm not sure how to do that - please advise?

**Comment by zkrige** [comment]
in your workflow.yaml file just hardcode a tag for testing purpose

or, remove the tag


```- name: Upload mac binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/mac/*.zip
          tag: ${{ github.ref }} #<---- here
          overwrite: true
          file_glob: true
```

**Comment by zkrige** [comment]
(╯°□°）╯︵ ┻━┻ 

wow. I have no idea

**Comment by tharatau** [comment]
[https://github.com/actions/first-interaction/issues/10
Looks like](https://github.com/actions/first-interaction/issues/10#issuecomment-546628432)

**Comment by tharatau** [comment]
Could try merging and if it fails, maybe revert the PR?

**Comment by tharatau** [comment]
Beat me to it lol

**Pull request merged**
