### PR TITLE
Run apt-get update on build runner

### PR DESCRIPTION
**Pull request by Ld-Hagen**
Additional step required to prevent package installation failures as described on https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners

### CODE REVIEW

**Comment by zkrige** [comment]
I see nothing wrong with this pr. But also. Our builds are currently not failing so I'm wary of fixing something that isn't broken

@ayushmanchhabra what is your thoughts?

**Comment by Ld-Hagen** [comment]
You may try right now and it will fail. At least yesterday it tried to install some packages that were removed from repository recently.

**Comment by zkrige** [comment]
Interesting - our action ran successfully a few days ago - https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/actions/runs/5908509156

**Comment by Ld-Hagen** [comment]
> Interesting - our action ran successfully a few days ago - https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/actions/runs/5908509156

Strange. For me it tried to install  **aspnetcore-targeting-pack-6.0** and  **aspnetcore-targeting-pack-7.0**
```
The following additional packages will be installed:
  aspnetcore-targeting-pack-6.0 aspnetcore-targeting-pack-7.0
The following packages will be REMOVED:
  aspnetcore-runtime-6.0 aspnetcore-runtime-7.0 dotnet-apphost-pack-6.0
  dotnet-apphost-pack-7.0 dotnet-host dotnet-hostfxr-6.0 dotnet-hostfxr-7.0
  dotnet-runtime-6.0 dotnet-runtime-7.0 dotnet-runtime-deps-6.0
  dotnet-runtime-deps-7.0 dotnet-sdk-6.0 dotnet-sdk-7.0
  dotnet-targeting-pack-6.0 dotnet-targeting-pack-7.0
The following packages will be upgraded:
  aspnetcore-targeting-pack-6.0 aspnetcore-targeting-pack-7.0
2 upgraded, 0 newly installed, 15 to remove and 17 not upgraded.
Need to get 3041 kB of archives.
After this operation, 990 MB disk space will be freed.
Ign:1 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-6.0 amd64 6.0.120-0ubuntu1~22.04.1
Ign:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-7.0 amd64 7.0.109-0ubuntu1~22.04.1
Err:1 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-6.0 amd64 6.0.120-0ubuntu1~22.04.1
  404  Not Found [IP: 52.252.75.106 80]
Err:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-7.0 amd64 7.0.109-0ubuntu1~22.04.1
  404  Not Found [IP: 52.252.75.106 80]
E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/universe/d/dotnet6/aspnetcore-targeting-pack-6.0_6.0.120-0ubuntu1%7e22.04.1_amd64.deb](http://azure.archive.ubuntu.com/ubuntu/pool/universe/d/dotnet6/aspnetcore-targeting-pack-6.0_6.0.120-0ubuntu1~22.04.1_amd64.deb)  404  Not Found [IP: 52.252.75.106 80]
E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/universe/d/dotnet7/aspnetcore-targeting-pack-7.0_7.0.109-0ubuntu1%7e22.04.1_amd64.deb](http://azure.archive.ubuntu.com/ubuntu/pool/universe/d/dotnet7/aspnetcore-targeting-pack-7.0_7.0.109-0ubuntu1~22.04.1_amd64.deb)  404  Not Found [IP: 52.252.75.106 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

**Comment by zkrige** [comment]
is this log output from your local linux machine or a GitHub hosted runner?

**Comment by Ld-Hagen** [comment]
> is this log output from your local linux machine or a GitHub hosted runner?

From GitHub hosted runner.
I guess I've found the cause of the problem with those packages (cleanup settings). But anyway it may happen with others.

**Comment by zkrige** [comment]
Personally I dont see anything wrong. I'm just wary of adding fixes for things that aren't broken (yet).

I'd prefer to take a more cautious approach. if it happens in future then we can definitely add this

**Comment by ayushmanchhabra** [comment]
> Personally I dont see anything wrong. I'm just wary of adding fixes for things that aren't broken (yet).
> 
> I'd prefer to take a more cautious approach. if it happens in future then we can definitely add this

@zkrige I agree

**Pull request closed without merging**
